---
# Setup Jenkins master node environment
- name: Configure Jenkins from configuration-as-a-code-plugin
  template:
    src: jenkins.yaml.j2
    dest: "{{ jenkins_home }}/jenkins.yaml"

- name: Restart jenkins to pickup a changes
  systemd:
    state: restarted
    daemon_reload: true
    name: jenkins

- name: Ensure that plugins is ready
  uri:
    url: "http://{{jenkins_hostname}}:{{jenkins_http_port}}{{jenkins_url_prefix}}}/credentials/store/system/domain/_/createCredentials"
    status_code: 405
  register: result
  until: result.status == 405
  retries: 60
  delay: 1

- name: Add Jenkins SSH credentials
  uri:
    url: http://{{jenkins_hostname}}:{{jenkins_http_port}}{{jenkins_url_prefix}}/credentials/store/system/domain/_/createCredentials
    method: POST
    user: "{{jenkins_slave_user_name}}"
    password: "{{jenkins_slave_user_password}}"
    body: "{{lookup('template', 'templates/add_credential.j2')}}"
    validate_certs: false
    body_format: form-urlencoded
    force_basic_auth: true
    status_code: 200, 302, 304

